Repository kubesphere/image-sync-config, pull requests merged in 2021-09, with the labels that each got.

#13 add nginx ingress controller
  rules/dockerhub/ingress.yaml
Labels: size/XS, lgtm, approved

#15 update kubefed image
  rules/kubespheredev2kubesphere.yaml
Labels: size/XS, lgtm, approved

#14 upgrade images associated with kubernetes v1.22.1
  rules/aliyun/k8s.yaml
Labels: lgtm, size/S, approved

#16 Sync snapshot-controller image to aliyun
  rules/aliyun/storage.yaml
Labels: size/XS, lgtm, approved

#17 sync kiali image from quay.io to kubesphere
  rules/dockerhub/kiali.yaml
Labels: size/XS, lgtm, approved

#18 sync kiali v1.28.1
  rules/dockerhub/kiali.yaml
Labels: size/XS, approved
