Repository kubesphere/image-sync-config, pull requests merged in 2022-01, with the labels that each got.

#22 Sync storageclass-accessor image to dockerhub.
  rules/custom2kubespheredev/storageclass-accessor.yaml
Labels: size/XS

#21 Update ingress.yaml
  rules/dockerhub/ingress.yaml
Labels: size/XS, approved

#23 sync kube-events images
  rules/kubespheredev2kubesphere.yaml
Labels: size/XS

#25 sync notification images to kubesphere
  rules/kubespheredev2kubesphere.yaml
Labels: size/XS, lgtm, approved
